
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const GET_COMMENTS = "GET_COMMENTS"
export const GET_TOP_COMMENT = "GET_TOP_COMMENT"

export const SET_CURRENT_TIME = "SET_CURRENT_TIME"